### ISSUE TITLE
Lustig ...

### ISSUE THREAD

**Issue by NMarkgraf** [UweZiegenhagen/LaTeXEinsteigerKurs#1]
Hallo Herr Ziegenhagen,

ich finde Ihre Werk wirklich gut. Das vorweg, aber finden Sie es nicht lustig, ein Werk zu schreiben und den Leuten LaTeX anzupreisen, weil es, da stimme ich Ihnen zu, super ist zum Setzen von Schriftstücken. Und dieses Werk dann in Markdown zu verfassen? ;-)

Viele Grüße
N. Markgraf

**Comment by UweZiegenhagen** [comment]
Vielen Dank! Aber zum Präsentieren von Inhalten im Netz ist HTML/MD doch noch ein wenig besser geeignet als PDF. Irgendwann schalte ich vllt. mal auf LaTeX mit HTML-Export um.
